version: '3'
services:
    chaintalkBootSrv:                       # Service Name
        container_name: chaintalk-boot-srv
        hostname: chaintalk-boot-srv
        build:
            context: .
        image: chaintalk-boot-srv:latest
        ports:
            # 指定端口映射，类似 docker run 的 -p 选项，注意使用字符串形式
            # [local port]:[container port]
            - "8011:8011"
        volumes:
            #- ./deploy/etc/localtime:/etc/localtime:ro
            #- ./deploy/etc/timezone:/etc/timezone:ro
            #- ./deploy/etc/hosts:/etc/hosts:ro
            - ./deploy/etc/chaintalk/.peerId:/etc/chaintalk/.peerId:ro
            - ./deploy/etc/chaintalk/.swarmKey:/etc/chaintalk/.swarmKey:ro
#        environment:
#            - LISTEN_PORT=8011
#            - FILE_PEER_ID=/etc/chaintalk/.peerId
#            - FILE_SWARM_KEY=/etc/chaintalk/.swarmKey
#            - ANNOUNCE_MULTIADDRS=
